# Generated by Django 3.2.4 on 2022-11-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20221129_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeddrink',
            name='liked',
            field=models.CharField(max_length=7),
        ),
    ]
