# Generated by Django 3.2.4 on 2023-01-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_comment_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l', models.CharField(max_length=900)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
